default_platform(:ios)

platform :ios do
  desc "Run Unit Tests"
  lane :test do
    scan(
  scheme: "MySimpleIosApp",
  devices: ["iPhone 16"],
  destination: "platform=iOS Simulator,id=7D41B4B1-2119-48A5-9F5D-FC4334F2BD51",
  fail_build: true
)

  end

  desc "Build the iOS app"
  lane :build do
    gym(
      scheme: "MySimpleIosApp",
      clean: true,
      output_directory: "./build",
      output_name: "MySimpleIosApp.ipa",
      configuration: "Release"   # Ensures it's a proper release build
    )
  end
end
