default_platform(:ios)

platform :ios do
  desc "Run Unit Tests"
  lane :test do
    scan(
      scheme: "MySimpleIosApp",
      devices: ["iPhone 16"]
    )
  end

  desc "Build the iOS app"
  lane :build do
    gym(
      scheme: "MySimpleIosApp",
      clean: true,
      output_directory: "./build",
      output_name: "MySimpleIosApp.ipa"
    )
  end
end

