default_platform(:ios)

platform :ios do
  desc "Run Unit Tests"
  lane :test do
    scan(
      scheme: "MySimpleIosApp",
      devices: ["iPhone 16"],
      clean: true,
      skip_detect_devices: true,  # Prevents issues if no real devices are connected
      fail_build: true            # Ensures Jenkins fails if tests fail
    )
  end

  desc "Build the iOS app"
  lane :build do
    gym(
      scheme: "MySimpleIosApp",
      clean: true,
      output_directory: "./build",
      output_name: "MySimpleIosApp.ipa",
      configuration: "Release"   # Ensures it's a proper release build
    )
  end
end
